/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\Ryan\\Desktop\\useful stuff\\github\\wiki\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-92a8f3a8",
    path: "/about/mapping-supports.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-92a8f3a8").then(next)
    },
  },
  {
    name: "v-696c52d2",
    path: "/about/3d-artists.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-696c52d2").then(next)
    },
  },
  {
    name: "v-793fd6f8",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-793fd6f8").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-34329735",
    path: "/about/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-34329735").then(next)
    },
  },
  {
    path: "/about/index.html",
    redirect: "/about/"
  },
  {
    name: "v-5d5addca",
    path: "/about/modders.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5d5addca").then(next)
    },
  },
  {
    name: "v-b3e34e54",
    path: "/about/moderators.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b3e34e54").then(next)
    },
  },
  {
    name: "v-f80bf164",
    path: "/about/event-winner.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f80bf164").then(next)
    },
  },
  {
    name: "v-6789f4ac",
    path: "/about/translators.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6789f4ac").then(next)
    },
  },
  {
    name: "v-fb5be62c",
    path: "/about/supports.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fb5be62c").then(next)
    },
  },
  {
    name: "v-ada3006c",
    path: "/about/staff.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ada3006c").then(next)
    },
  },
  {
    name: "v-018236d2",
    path: "/beginners-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-018236d2").then(next)
    },
  },
  {
    name: "v-545a88ac",
    path: "/communities/community-hub.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-545a88ac").then(next)
    },
  },
  {
    name: "v-5a7b76fe",
    path: "/communities/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5a7b76fe").then(next)
    },
  },
  {
    path: "/communities/index.html",
    redirect: "/communities/"
  },
  {
    name: "v-61f6b472",
    path: "/de/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-61f6b472").then(next)
    },
  },
  {
    path: "/de/index.html",
    redirect: "/de/"
  },
  {
    name: "v-943ff850",
    path: "/communities/regional-hub.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-943ff850").then(next)
    },
  },
  {
    name: "v-61cb8f3a",
    path: "/de/about/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-61cb8f3a").then(next)
    },
  },
  {
    path: "/de/about/index.html",
    redirect: "/de/about/"
  },
  {
    name: "v-167bc4b1",
    path: "/de/about/3d-artists.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-167bc4b1").then(next)
    },
  },
  {
    name: "v-3d9ac61e",
    path: "/de/about/event-winner.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3d9ac61e").then(next)
    },
  },
  {
    name: "v-1d53415e",
    path: "/de/about/mapping-supports.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1d53415e").then(next)
    },
  },
  {
    name: "v-ad805f86",
    path: "/de/about/staff.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ad805f86").then(next)
    },
  },
  {
    name: "v-3ae33375",
    path: "/de/about/modders.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3ae33375").then(next)
    },
  },
  {
    name: "v-5fcbb271",
    path: "/de/about/moderators.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5fcbb271").then(next)
    },
  },
  {
    name: "v-22f4f49e",
    path: "/de/about/supports.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-22f4f49e").then(next)
    },
  },
  {
    name: "v-66b1ee2c",
    path: "/de/beginners-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-66b1ee2c").then(next)
    },
  },
  {
    name: "v-273e018c",
    path: "/de/communities/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-273e018c").then(next)
    },
  },
  {
    path: "/de/communities/index.html",
    redirect: "/de/communities/"
  },
  {
    name: "v-0557338b",
    path: "/de/about/translators.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0557338b").then(next)
    },
  },
  {
    name: "v-63f96067",
    path: "/de/communities/community-hub.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-63f96067").then(next)
    },
  },
  {
    name: "v-24dafe11",
    path: "/de/faq/install-folder.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-24dafe11").then(next)
    },
  },
  {
    name: "v-478b134c",
    path: "/de/faq/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-478b134c").then(next)
    },
  },
  {
    path: "/de/faq/index.html",
    redirect: "/de/faq/"
  },
  {
    name: "v-5912c011",
    path: "/de/communities/regional-hub.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5912c011").then(next)
    },
  },
  {
    name: "v-2d0ddf78",
    path: "/de/grips-and-tricks.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d0ddf78").then(next)
    },
  },
  {
    name: "v-3322ca0d",
    path: "/de/mapping/advanced-lighting.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3322ca0d").then(next)
    },
  },
  {
    name: "v-845d159e",
    path: "/de/mapping/advanced-audio.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-845d159e").then(next)
    },
  },
  {
    name: "v-3697d9da",
    path: "/de/health-and-safety.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3697d9da").then(next)
    },
  },
  {
    name: "v-2678ab4c",
    path: "/de/mapping/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2678ab4c").then(next)
    },
  },
  {
    path: "/de/mapping/index.html",
    redirect: "/de/mapping/"
  },
  {
    name: "v-5f203931",
    path: "/de/mapping/basic-lighting.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5f203931").then(next)
    },
  },
  {
    name: "v-428fa466",
    path: "/de/mapping/basic-audio.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-428fa466").then(next)
    },
  },
  {
    name: "v-5628f746",
    path: "/de/mapping/basic-mapping.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5628f746").then(next)
    },
  },
  {
    name: "v-7d3e1b66",
    path: "/de/mapping/editor-keybinds.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7d3e1b66").then(next)
    },
  },
  {
    name: "v-7c97aa91",
    path: "/de/mapping/glossary.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7c97aa91").then(next)
    },
  },
  {
    name: "v-36637b11",
    path: "/de/mapping/extended-mapping.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-36637b11").then(next)
    },
  },
  {
    name: "v-17e81905",
    path: "/de/mapping/how-to-testplay.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-17e81905").then(next)
    },
  },
  {
    name: "v-4402808a",
    path: "/de/mapping/intermediate-lighting.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4402808a").then(next)
    },
  },
  {
    name: "v-027b05d5",
    path: "/de/mapping/lighting-defaults.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-027b05d5").then(next)
    },
  },
  {
    name: "v-5f6da391",
    path: "/de/mapping/intermediate-mapping.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5f6da391").then(next)
    },
  },
  {
    name: "v-2b7c3e91",
    path: "/de/mapping/map-format.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2b7c3e91").then(next)
    },
  },
  {
    name: "v-3a13bb85",
    path: "/de/mapping/mapping-credits.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3a13bb85").then(next)
    },
  },
  {
    name: "v-8b8b94de",
    path: "/de/mapping/mediocre-map-assistant.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8b8b94de").then(next)
    },
  },
  {
    name: "v-21a95f1a",
    path: "/de/modding/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-21a95f1a").then(next)
    },
  },
  {
    path: "/de/modding/index.html",
    redirect: "/de/modding/"
  },
  {
    name: "v-c079d6be",
    path: "/de/mapping/mapping-anxiety.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c079d6be").then(next)
    },
  },
  {
    name: "v-03646abf",
    path: "/de/modding/intro.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-03646abf").then(next)
    },
  },
  {
    name: "v-f64d58a2",
    path: "/de/modding/linux.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f64d58a2").then(next)
    },
  },
  {
    name: "v-e572cd5c",
    path: "/de/models/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e572cd5c").then(next)
    },
  },
  {
    path: "/de/models/index.html",
    redirect: "/de/models/"
  },
  {
    name: "v-21106477",
    path: "/de/models/avatars-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-21106477").then(next)
    },
  },
  {
    name: "v-9454780e",
    path: "/de/models/custom-avatars.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9454780e").then(next)
    },
  },
  {
    name: "v-8ee491aa",
    path: "/de/models/custom-notes.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8ee491aa").then(next)
    },
  },
  {
    name: "v-fef75e26",
    path: "/de/models/custom-platforms.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fef75e26").then(next)
    },
  },
  {
    name: "v-3d1cd8d2",
    path: "/de/models/custom-sabers.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3d1cd8d2").then(next)
    },
  },
  {
    name: "v-64ed58db",
    path: "/de/models/custom-walls.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-64ed58db").then(next)
    },
  },
  {
    name: "v-ff3288d2",
    path: "/de/models/notes-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ff3288d2").then(next)
    },
  },
  {
    name: "v-612599b7",
    path: "/de/models/platforms-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-612599b7").then(next)
    },
  },
  {
    name: "v-613314c4",
    path: "/de/pc-modding.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-613314c4").then(next)
    },
  },
  {
    name: "v-3fdf276e",
    path: "/de/not-available.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3fdf276e").then(next)
    },
  },
  {
    name: "v-916fc73c",
    path: "/de/quest-modding.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-916fc73c").then(next)
    },
  },
  {
    name: "v-e36efa1a",
    path: "/de/models/sabers-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e36efa1a").then(next)
    },
  },
  {
    name: "v-13eae3ba",
    path: "/de/support/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-13eae3ba").then(next)
    },
  },
  {
    path: "/de/support/index.html",
    redirect: "/de/support/"
  },
  {
    name: "v-2ddafd42",
    path: "/de/ranking-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2ddafd42").then(next)
    },
  },
  {
    name: "v-4c739e31",
    path: "/de/support/exceptions.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4c739e31").then(next)
    },
  },
  {
    name: "v-3d624c3a",
    path: "/faq/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3d624c3a").then(next)
    },
  },
  {
    path: "/faq/index.html",
    redirect: "/faq/"
  },
  {
    name: "v-3edea0c4",
    path: "/faq/install-folder.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3edea0c4").then(next)
    },
  },
  {
    name: "v-224ccfe7",
    path: "/fr/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-224ccfe7").then(next)
    },
  },
  {
    path: "/fr/index.html",
    redirect: "/fr/"
  },
  {
    name: "v-290a2851",
    path: "/fr/about/3d-artists.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-290a2851").then(next)
    },
  },
  {
    name: "v-680cd751",
    path: "/fr/about/event-winner.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-680cd751").then(next)
    },
  },
  {
    name: "v-55341731",
    path: "/fr/about/mapping-supports.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-55341731").then(next)
    },
  },
  {
    name: "v-c8f8c5cc",
    path: "/fr/about/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c8f8c5cc").then(next)
    },
  },
  {
    path: "/fr/about/index.html",
    redirect: "/fr/about/"
  },
  {
    name: "v-c5dadac2",
    path: "/fr/about/modders.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c5dadac2").then(next)
    },
  },
  {
    name: "v-725a1611",
    path: "/fr/about/moderators.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-725a1611").then(next)
    },
  },
  {
    name: "v-4e829327",
    path: "/fr/about/staff.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4e829327").then(next)
    },
  },
  {
    name: "v-6c07fade",
    path: "/fr/about/supports.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6c07fade").then(next)
    },
  },
  {
    name: "v-6fad0996",
    path: "/fr/about/translators.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6fad0996").then(next)
    },
  },
  {
    name: "v-29bb0cd4",
    path: "/fr/beginners-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-29bb0cd4").then(next)
    },
  },
  {
    name: "v-08b8fe4c",
    path: "/fr/communities/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-08b8fe4c").then(next)
    },
  },
  {
    path: "/fr/communities/index.html",
    redirect: "/fr/communities/"
  },
  {
    name: "v-50883911",
    path: "/fr/communities/community-hub.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-50883911").then(next)
    },
  },
  {
    name: "v-a8958f1e",
    path: "/fr/faq/install-folder.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a8958f1e").then(next)
    },
  },
  {
    name: "v-18bdd2fa",
    path: "/fr/faq/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-18bdd2fa").then(next)
    },
  },
  {
    path: "/fr/faq/index.html",
    redirect: "/fr/faq/"
  },
  {
    name: "v-07f11838",
    path: "/fr/grips-and-tricks.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-07f11838").then(next)
    },
  },
  {
    name: "v-c30b0d0c",
    path: "/fr/mapping/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c30b0d0c").then(next)
    },
  },
  {
    path: "/fr/mapping/index.html",
    redirect: "/fr/mapping/"
  },
  {
    name: "v-0d2bbcf8",
    path: "/fr/health-and-safety.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d2bbcf8").then(next)
    },
  },
  {
    name: "v-21af2d11",
    path: "/fr/mapping/advanced-audio.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-21af2d11").then(next)
    },
  },
  {
    name: "v-1fb1a2b7",
    path: "/fr/mapping/advanced-lighting.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1fb1a2b7").then(next)
    },
  },
  {
    name: "v-504e7c92",
    path: "/fr/mapping/basic-audio.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-504e7c92").then(next)
    },
  },
  {
    name: "v-7a041dde",
    path: "/fr/mapping/basic-lighting.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7a041dde").then(next)
    },
  },
  {
    name: "v-85da16f2",
    path: "/fr/mapping/basic-mapping.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-85da16f2").then(next)
    },
  },
  {
    name: "v-91d86292",
    path: "/fr/mapping/editor-keybinds.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-91d86292").then(next)
    },
  },
  {
    name: "v-763e4c9e",
    path: "/fr/mapping/extended-mapping.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-763e4c9e").then(next)
    },
  },
  {
    name: "v-e1b3e39e",
    path: "/fr/mapping/glossary.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e1b3e39e").then(next)
    },
  },
  {
    name: "v-0d9af56f",
    path: "/fr/mapping/how-to-testplay.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d9af56f").then(next)
    },
  },
  {
    name: "v-186740e5",
    path: "/fr/mapping/intermediate-lighting.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-186740e5").then(next)
    },
  },
  {
    name: "v-2aaa1fb1",
    path: "/fr/mapping/intermediate-mapping.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2aaa1fb1").then(next)
    },
  },
  {
    name: "v-9b530e1e",
    path: "/fr/mapping/map-format.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9b530e1e").then(next)
    },
  },
  {
    name: "v-21ec4302",
    path: "/fr/mapping/lighting-defaults.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-21ec4302").then(next)
    },
  },
  {
    name: "v-d5141dea",
    path: "/fr/mapping/mapping-anxiety.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d5141dea").then(next)
    },
  },
  {
    name: "v-2fc697ef",
    path: "/fr/mapping/mapping-credits.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2fc697ef").then(next)
    },
  },
  {
    name: "v-3b7e2871",
    path: "/fr/mapping/mediocre-map-assistant.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b7e2871").then(next)
    },
  },
  {
    name: "v-593fa38c",
    path: "/fr/modding/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-593fa38c").then(next)
    },
  },
  {
    path: "/fr/modding/index.html",
    redirect: "/fr/modding/"
  },
  {
    name: "v-6593c9e9",
    path: "/fr/modding/intro.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6593c9e9").then(next)
    },
  },
  {
    name: "v-31ee9a4e",
    path: "/fr/modding/linux.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-31ee9a4e").then(next)
    },
  },
  {
    name: "v-c40597ba",
    path: "/fr/models/custom-avatars.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c40597ba").then(next)
    },
  },
  {
    name: "v-17bb1068",
    path: "/fr/models/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-17bb1068").then(next)
    },
  },
  {
    path: "/fr/models/index.html",
    redirect: "/fr/models/"
  },
  {
    name: "v-dc4334d2",
    path: "/fr/models/avatars-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dc4334d2").then(next)
    },
  },
  {
    name: "v-9ca369d6",
    path: "/fr/models/custom-notes.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9ca369d6").then(next)
    },
  },
  {
    name: "v-76372d57",
    path: "/fr/models/custom-platforms.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-76372d57").then(next)
    },
  },
  {
    name: "v-523f94b7",
    path: "/fr/models/custom-sabers.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-523f94b7").then(next)
    },
  },
  {
    name: "v-5e0decc5",
    path: "/fr/models/custom-walls.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5e0decc5").then(next)
    },
  },
  {
    name: "v-0740f5f7",
    path: "/fr/models/notes-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0740f5f7").then(next)
    },
  },
  {
    name: "v-75f95cd2",
    path: "/fr/models/platforms-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-75f95cd2").then(next)
    },
  },
  {
    name: "v-f12dd246",
    path: "/fr/models/sabers-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f12dd246").then(next)
    },
  },
  {
    name: "v-bbe2f2d0",
    path: "/fr/not-available.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bbe2f2d0").then(next)
    },
  },
  {
    name: "v-2974d7b8",
    path: "/fr/pc-modding.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2974d7b8").then(next)
    },
  },
  {
    name: "v-19777b8c",
    path: "/fr/quest-modding.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-19777b8c").then(next)
    },
  },
  {
    name: "v-dfeb4728",
    path: "/fr/ranking-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dfeb4728").then(next)
    },
  },
  {
    name: "v-59644ede",
    path: "/fr/support/exceptions.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-59644ede").then(next)
    },
  },
  {
    name: "v-74bc9a4c",
    path: "/fr/support/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-74bc9a4c").then(next)
    },
  },
  {
    path: "/fr/support/index.html",
    redirect: "/fr/support/"
  },
  {
    name: "v-0ab24eff",
    path: "/grips-and-tricks.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0ab24eff").then(next)
    },
  },
  {
    name: "v-48506077",
    path: "/health-and-safety.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-48506077").then(next)
    },
  },
  {
    name: "v-9dfb73f2",
    path: "/ja/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9dfb73f2").then(next)
    },
  },
  {
    path: "/ja/index.html",
    redirect: "/ja/"
  },
  {
    name: "v-9e85301e",
    path: "/ja/about/3d-artists.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9e85301e").then(next)
    },
  },
  {
    name: "v-08f9420c",
    path: "/ja/about/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-08f9420c").then(next)
    },
  },
  {
    path: "/ja/about/index.html",
    redirect: "/ja/about/"
  },
  {
    name: "v-fe9d79de",
    path: "/ja/about/mapping-supports.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fe9d79de").then(next)
    },
  },
  {
    name: "v-518a4cee",
    path: "/ja/about/modders.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-518a4cee").then(next)
    },
  },
  {
    name: "v-0be5549e",
    path: "/ja/about/moderators.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0be5549e").then(next)
    },
  },
  {
    name: "v-0de8a5d1",
    path: "/ja/about/staff.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0de8a5d1").then(next)
    },
  },
  {
    name: "v-2537d371",
    path: "/ja/about/supports.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2537d371").then(next)
    },
  },
  {
    name: "v-c450f680",
    path: "/ja/beginners-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c450f680").then(next)
    },
  },
  {
    name: "v-66be1e7a",
    path: "/ja/communities/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-66be1e7a").then(next)
    },
  },
  {
    path: "/ja/communities/index.html",
    redirect: "/ja/communities/"
  },
  {
    name: "v-0f3f897b",
    path: "/ja/communities/community-hub.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0f3f897b").then(next)
    },
  },
  {
    name: "v-ca170d5e",
    path: "/ja/communities/regional-hub.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ca170d5e").then(next)
    },
  },
  {
    name: "v-5be128cc",
    path: "/ja/faq/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5be128cc").then(next)
    },
  },
  {
    path: "/ja/faq/index.html",
    redirect: "/ja/faq/"
  },
  {
    name: "v-2464525e",
    path: "/ja/faq/install-folder.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2464525e").then(next)
    },
  },
  {
    name: "v-f88a98f8",
    path: "/ja/grips-and-tricks.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f88a98f8").then(next)
    },
  },
  {
    name: "v-75c280ee",
    path: "/ja/health-and-safety.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-75c280ee").then(next)
    },
  },
  {
    name: "v-7678749a",
    path: "/ja/mapping/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7678749a").then(next)
    },
  },
  {
    path: "/ja/mapping/index.html",
    redirect: "/ja/mapping/"
  },
  {
    name: "v-4d2c58f1",
    path: "/ja/mapping/advanced-audio.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4d2c58f1").then(next)
    },
  },
  {
    name: "v-432e19be",
    path: "/ja/mapping/advanced-lighting.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-432e19be").then(next)
    },
  },
  {
    name: "v-7191f53e",
    path: "/ja/mapping/basic-audio.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7191f53e").then(next)
    },
  },
  {
    name: "v-2309c61e",
    path: "/ja/mapping/basic-lighting.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2309c61e").then(next)
    },
  },
  {
    name: "v-33b4a71e",
    path: "/ja/mapping/basic-mapping.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-33b4a71e").then(next)
    },
  },
  {
    name: "v-fa54ea3e",
    path: "/ja/mapping/editor-keybinds.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fa54ea3e").then(next)
    },
  },
  {
    name: "v-78453451",
    path: "/ja/mapping/extended-mapping.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-78453451").then(next)
    },
  },
  {
    name: "v-16d94dd1",
    path: "/ja/mapping/glossary.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-16d94dd1").then(next)
    },
  },
  {
    name: "v-4d469cce",
    path: "/ja/mapping/how-to-testplay.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4d469cce").then(next)
    },
  },
  {
    name: "v-240d69cf",
    path: "/ja/mapping/intermediate-lighting.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-240d69cf").then(next)
    },
  },
  {
    name: "v-25eab05e",
    path: "/ja/mapping/intermediate-mapping.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-25eab05e").then(next)
    },
  },
  {
    name: "v-1721d15e",
    path: "/ja/mapping/map-format.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1721d15e").then(next)
    },
  },
  {
    name: "v-a47da22e",
    path: "/ja/mapping/lighting-defaults.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a47da22e").then(next)
    },
  },
  {
    name: "v-6137ad35",
    path: "/ja/mapping/mapping-anxiety.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6137ad35").then(next)
    },
  },
  {
    name: "v-08ef57ce",
    path: "/ja/mapping/mapping-credits.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-08ef57ce").then(next)
    },
  },
  {
    name: "v-7fdbaf51",
    path: "/ja/mapping/mediocre-map-assistant.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7fdbaf51").then(next)
    },
  },
  {
    name: "v-a943ad4c",
    path: "/ja/modding/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a943ad4c").then(next)
    },
  },
  {
    path: "/ja/modding/index.html",
    redirect: "/ja/modding/"
  },
  {
    name: "v-30dfc29e",
    path: "/fr/communities/regional-hub.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-30dfc29e").then(next)
    },
  },
  {
    name: "v-68dea99e",
    path: "/ja/modding/extras.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-68dea99e").then(next)
    },
  },
  {
    name: "v-c087de5a",
    path: "/ja/modding/intro.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c087de5a").then(next)
    },
  },
  {
    name: "v-54b9f7be",
    path: "/ja/models/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-54b9f7be").then(next)
    },
  },
  {
    path: "/ja/models/index.html",
    redirect: "/ja/models/"
  },
  {
    name: "v-2130f9c3",
    path: "/ja/modding/linux.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2130f9c3").then(next)
    },
  },
  {
    name: "v-703e52b7",
    path: "/ja/models/avatars-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-703e52b7").then(next)
    },
  },
  {
    name: "v-71e027e6",
    path: "/ja/models/custom-avatars.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-71e027e6").then(next)
    },
  },
  {
    name: "v-bde6e282",
    path: "/ja/models/custom-notes.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bde6e282").then(next)
    },
  },
  {
    name: "v-41f8e981",
    path: "/ja/models/custom-platforms.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-41f8e981").then(next)
    },
  },
  {
    name: "v-309f81d7",
    path: "/ja/models/custom-sabers.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-309f81d7").then(next)
    },
  },
  {
    name: "v-4d6c306f",
    path: "/ja/models/custom-walls.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4d6c306f").then(next)
    },
  },
  {
    name: "v-49599457",
    path: "/ja/models/notes-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-49599457").then(next)
    },
  },
  {
    name: "v-539fc276",
    path: "/ja/quest-modding.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-539fc276").then(next)
    },
  },
  {
    name: "v-2e8c5784",
    path: "/ja/pc-modding.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2e8c5784").then(next)
    },
  },
  {
    name: "v-76c75a87",
    path: "/ja/models/sabers-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-76c75a87").then(next)
    },
  },
  {
    name: "v-1eff0512",
    path: "/ja/models/platforms-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1eff0512").then(next)
    },
  },
  {
    name: "v-6b9ab954",
    path: "/ja/ranking-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6b9ab954").then(next)
    },
  },
  {
    name: "v-156676f1",
    path: "/ja/support/exceptions.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-156676f1").then(next)
    },
  },
  {
    name: "v-c4c0a40c",
    path: "/ja/support/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c4c0a40c").then(next)
    },
  },
  {
    path: "/ja/support/index.html",
    redirect: "/ja/support/"
  },
  {
    name: "v-0cf71a09",
    path: "/ja/support/new-support.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0cf71a09").then(next)
    },
  },
  {
    name: "v-23fccf73",
    path: "/mapping/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-23fccf73").then(next)
    },
  },
  {
    path: "/mapping/index.html",
    redirect: "/mapping/"
  },
  {
    name: "v-c867a6c4",
    path: "/mapping/advanced-audio.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c867a6c4").then(next)
    },
  },
  {
    name: "v-769e670a",
    path: "/mapping/advanced-lighting.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-769e670a").then(next)
    },
  },
  {
    name: "v-7cb75d8a",
    path: "/mapping/basic-audio.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7cb75d8a").then(next)
    },
  },
  {
    name: "v-be43e2ec",
    path: "/mapping/editor-keybinds.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-be43e2ec").then(next)
    },
  },
  {
    name: "v-9e398444",
    path: "/mapping/basic-lighting.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9e398444").then(next)
    },
  },
  {
    name: "v-129749ec",
    path: "/mapping/basic-mapping.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-129749ec").then(next)
    },
  },
  {
    name: "v-3b2f3eea",
    path: "/mapping/intermediate-lighting.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b2f3eea").then(next)
    },
  },
  {
    name: "v-e65ff5ec",
    path: "/mapping/how-to-testplay.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e65ff5ec").then(next)
    },
  },
  {
    name: "v-3823ecf8",
    path: "/mapping/glossary.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3823ecf8").then(next)
    },
  },
  {
    name: "v-5ea012c0",
    path: "/mapping/extended-mapping.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ea012c0").then(next)
    },
  },
  {
    name: "v-70f1ffc0",
    path: "/mapping/intermediate-mapping.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-70f1ffc0").then(next)
    },
  },
  {
    name: "v-3e9d618a",
    path: "/mapping/lighting-defaults.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3e9d618a").then(next)
    },
  },
  {
    name: "v-35df85ec",
    path: "/mapping/mapping-credits.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-35df85ec").then(next)
    },
  },
  {
    name: "v-22a8276c",
    path: "/mapping/mapping-anxiety.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-22a8276c").then(next)
    },
  },
  {
    name: "v-331eb46c",
    path: "/mapping/mediocre-map-assistant.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-331eb46c").then(next)
    },
  },
  {
    name: "v-b16e2d38",
    path: "/mapping/map-format.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b16e2d38").then(next)
    },
  },
  {
    name: "v-38a1bfe2",
    path: "/modding/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-38a1bfe2").then(next)
    },
  },
  {
    path: "/modding/index.html",
    redirect: "/modding/"
  },
  {
    name: "v-18a6702a",
    path: "/modding/linux.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-18a6702a").then(next)
    },
  },
  {
    name: "v-6df99dac",
    path: "/modding/intro.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6df99dac").then(next)
    },
  },
  {
    name: "v-74ab3828",
    path: "/models/avatars-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-74ab3828").then(next)
    },
  },
  {
    name: "v-4fc8a738",
    path: "/models/custom-avatars.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4fc8a738").then(next)
    },
  },
  {
    name: "v-45297027",
    path: "/models/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-45297027").then(next)
    },
  },
  {
    path: "/models/index.html",
    redirect: "/models/"
  },
  {
    name: "v-51131738",
    path: "/models/custom-platforms.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-51131738").then(next)
    },
  },
  {
    name: "v-a4363ff8",
    path: "/models/custom-notes.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a4363ff8").then(next)
    },
  },
  {
    name: "v-ad819a44",
    path: "/models/custom-sabers.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ad819a44").then(next)
    },
  },
  {
    name: "v-9671d748",
    path: "/models/platforms-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9671d748").then(next)
    },
  },
  {
    name: "v-4fa4291a",
    path: "/models/notes-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4fa4291a").then(next)
    },
  },
  {
    name: "v-64dcaf84",
    path: "/models/sabers-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-64dcaf84").then(next)
    },
  },
  {
    name: "v-993ae5f8",
    path: "/models/custom-walls.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-993ae5f8").then(next)
    },
  },
  {
    name: "v-13b75ea7",
    path: "/nl/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-13b75ea7").then(next)
    },
  },
  {
    path: "/nl/index.html",
    redirect: "/nl/"
  },
  {
    name: "v-05fc434c",
    path: "/nl/about/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-05fc434c").then(next)
    },
  },
  {
    path: "/nl/about/index.html",
    redirect: "/nl/about/"
  },
  {
    name: "v-c21e2fde",
    path: "/nl/about/3d-artists.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c21e2fde").then(next)
    },
  },
  {
    name: "v-5fd6a8de",
    path: "/nl/about/event-winner.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5fd6a8de").then(next)
    },
  },
  {
    name: "v-ca4c171e",
    path: "/nl/about/mapping-supports.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ca4c171e").then(next)
    },
  },
  {
    name: "v-2346298a",
    path: "/nl/about/modders.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2346298a").then(next)
    },
  },
  {
    name: "v-9f7f645e",
    path: "/nl/about/supports.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9f7f645e").then(next)
    },
  },
  {
    name: "v-042d9e43",
    path: "/nl/about/staff.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-042d9e43").then(next)
    },
  },
  {
    name: "v-2f7e545e",
    path: "/nl/about/moderators.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2f7e545e").then(next)
    },
  },
  {
    name: "v-b9a0e25e",
    path: "/nl/about/translators.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b9a0e25e").then(next)
    },
  },
  {
    name: "v-59087fb2",
    path: "/nl/beginners-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-59087fb2").then(next)
    },
  },
  {
    name: "v-62ba1f1e",
    path: "/nl/communities/regional-hub.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-62ba1f1e").then(next)
    },
  },
  {
    name: "v-fb9456cc",
    path: "/nl/communities/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fb9456cc").then(next)
    },
  },
  {
    path: "/nl/communities/index.html",
    redirect: "/nl/communities/"
  },
  {
    name: "v-f44b7aa6",
    path: "/nl/communities/community-hub.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f44b7aa6").then(next)
    },
  },
  {
    name: "v-4ed50e8c",
    path: "/nl/faq/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4ed50e8c").then(next)
    },
  },
  {
    path: "/nl/faq/index.html",
    redirect: "/nl/faq/"
  },
  {
    name: "v-13bd0cb1",
    path: "/nl/faq/install-folder.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-13bd0cb1").then(next)
    },
  },
  {
    name: "v-71ee33a4",
    path: "/nl/grips-and-tricks.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-71ee33a4").then(next)
    },
  },
  {
    name: "v-4ff4b63a",
    path: "/nl/mapping/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4ff4b63a").then(next)
    },
  },
  {
    path: "/nl/mapping/index.html",
    redirect: "/nl/mapping/"
  },
  {
    name: "v-571f95c0",
    path: "/nl/health-and-safety.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-571f95c0").then(next)
    },
  },
  {
    name: "v-67550a51",
    path: "/nl/mapping/advanced-audio.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-67550a51").then(next)
    },
  },
  {
    name: "v-23e97a5a",
    path: "/nl/mapping/basic-audio.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-23e97a5a").then(next)
    },
  },
  {
    name: "v-5503ac53",
    path: "/nl/mapping/advanced-lighting.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5503ac53").then(next)
    },
  },
  {
    name: "v-08a3ce51",
    path: "/nl/mapping/basic-lighting.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-08a3ce51").then(next)
    },
  },
  {
    name: "v-eff379ba",
    path: "/nl/mapping/basic-mapping.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-eff379ba").then(next)
    },
  },
  {
    name: "v-09e44ad3",
    path: "/nl/mapping/editor-keybinds.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-09e44ad3").then(next)
    },
  },
  {
    name: "v-a818a91e",
    path: "/nl/mapping/extended-mapping.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a818a91e").then(next)
    },
  },
  {
    name: "v-606b718b",
    path: "/nl/mapping/how-to-testplay.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-606b718b").then(next)
    },
  },
  {
    name: "v-050ccdf1",
    path: "/nl/mapping/glossary.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-050ccdf1").then(next)
    },
  },
  {
    name: "v-26c98581",
    path: "/nl/mapping/intermediate-lighting.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-26c98581").then(next)
    },
  },
  {
    name: "v-27aaba71",
    path: "/nl/mapping/intermediate-mapping.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-27aaba71").then(next)
    },
  },
  {
    name: "v-245be81b",
    path: "/nl/mapping/lighting-defaults.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-245be81b").then(next)
    },
  },
  {
    name: "v-2f7325b2",
    path: "/nl/mapping/mapping-anxiety.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2f7325b2").then(next)
    },
  },
  {
    name: "v-1a5e4d31",
    path: "/nl/mapping/map-format.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1a5e4d31").then(next)
    },
  },
  {
    name: "v-6220d09e",
    path: "/nl/mapping/mediocre-map-assistant.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6220d09e").then(next)
    },
  },
  {
    name: "v-fad1d7ea",
    path: "/nl/mapping/mapping-credits.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fad1d7ea").then(next)
    },
  },
  {
    name: "v-f64b2a0c",
    path: "/nl/modding/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f64b2a0c").then(next)
    },
  },
  {
    path: "/nl/modding/index.html",
    redirect: "/nl/modding/"
  },
  {
    name: "v-38530b75",
    path: "/nl/modding/linux.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-38530b75").then(next)
    },
  },
  {
    name: "v-9243baf6",
    path: "/nl/modding/intro.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9243baf6").then(next)
    },
  },
  {
    name: "v-6e7dee57",
    path: "/nl/models/avatars-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e7dee57").then(next)
    },
  },
  {
    name: "v-4df2014c",
    path: "/nl/models/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4df2014c").then(next)
    },
  },
  {
    path: "/nl/models/index.html",
    redirect: "/nl/models/"
  },
  {
    name: "v-68f082bf",
    path: "/nl/models/custom-avatars.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-68f082bf").then(next)
    },
  },
  {
    name: "v-6df0ad1a",
    path: "/nl/models/custom-platforms.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6df0ad1a").then(next)
    },
  },
  {
    name: "v-703e679e",
    path: "/nl/models/custom-notes.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-703e679e").then(next)
    },
  },
  {
    name: "v-2edf1d77",
    path: "/nl/models/custom-sabers.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2edf1d77").then(next)
    },
  },
  {
    name: "v-74406de1",
    path: "/nl/models/custom-walls.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-74406de1").then(next)
    },
  },
  {
    name: "v-6f48ca37",
    path: "/nl/models/notes-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6f48ca37").then(next)
    },
  },
  {
    name: "v-0aa92ed7",
    path: "/nl/models/platforms-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0aa92ed7").then(next)
    },
  },
  {
    name: "v-194e4198",
    path: "/nl/not-available.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-194e4198").then(next)
    },
  },
  {
    name: "v-c4c8d00e",
    path: "/nl/models/sabers-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c4c8d00e").then(next)
    },
  },
  {
    name: "v-183e5338",
    path: "/nl/pc-modding.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-183e5338").then(next)
    },
  },
  {
    name: "v-6ac1d428",
    path: "/nl/quest-modding.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6ac1d428").then(next)
    },
  },
  {
    name: "v-3b55acd1",
    path: "/nl/support/exceptions.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b55acd1").then(next)
    },
  },
  {
    name: "v-3d5695f0",
    path: "/nl/ranking-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3d5695f0").then(next)
    },
  },
  {
    name: "v-771bef9a",
    path: "/nl/support/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-771bef9a").then(next)
    },
  },
  {
    path: "/nl/support/index.html",
    redirect: "/nl/support/"
  },
  {
    name: "v-21d67337",
    path: "/not-available.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-21d67337").then(next)
    },
  },
  {
    name: "v-6086f477",
    path: "/ranking-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6086f477").then(next)
    },
  },
  {
    name: "v-45b0ac12",
    path: "/pc-modding.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-45b0ac12").then(next)
    },
  },
  {
    name: "v-7ce48677",
    path: "/quest-modding.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ce48677").then(next)
    },
  },
  {
    name: "v-30df57f1",
    path: "/support/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-30df57f1").then(next)
    },
  },
  {
    path: "/support/index.html",
    redirect: "/support/"
  },
  {
    name: "v-fb2058a4",
    path: "/support/exceptions.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fb2058a4").then(next)
    },
  },
  {
    name: "v-91663668",
    path: "/support/modding-with-android.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-91663668").then(next)
    },
  },
  {
    name: "v-7d9c6f0a",
    path: "/support/new-support.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7d9c6f0a").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]